/* Generated by RuntimeBrowser on iPhone OS 4.0
 Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class CALayer;
#import <UIKit/UIView.h>

@interface UITableViewCellContentViewProxy : UIView 
{
    CALayer *_mask;
}

-(id) _cell;

@end

